//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.28 at 09:23:00 AM IST 
//


package biz.nable.sb.cor.transfer.soap.schemas.iib;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoanScheduleRecord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoanScheduleRecord"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcctNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlowID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FirstInstDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InstAmount" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="NoOfInst" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="NextDemandDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RepayCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RepayFrequency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoanScheduleRecord", propOrder = {
    "acctNo",
    "flowID",
    "firstInstDate",
    "instAmount",
    "noOfInst",
    "nextDemandDate",
    "repayCode",
    "repayFrequency"
})
public class LoanScheduleRecord {

    @XmlElement(name = "AcctNo", required = true)
    protected String acctNo;
    @XmlElement(name = "FlowID", required = true)
    protected String flowID;
    @XmlElement(name = "FirstInstDate", required = true)
    protected String firstInstDate;
    @XmlElement(name = "InstAmount")
    protected double instAmount;
    @XmlElement(name = "NoOfInst")
    protected int noOfInst;
    @XmlElement(name = "NextDemandDate", required = true)
    protected String nextDemandDate;
    @XmlElement(name = "RepayCode", required = true)
    protected String repayCode;
    @XmlElement(name = "RepayFrequency", required = true)
    protected String repayFrequency;

    /**
     * Gets the value of the acctNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * Sets the value of the acctNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNo(String value) {
        this.acctNo = value;
    }

    /**
     * Gets the value of the flowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowID() {
        return flowID;
    }

    /**
     * Sets the value of the flowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowID(String value) {
        this.flowID = value;
    }

    /**
     * Gets the value of the firstInstDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstInstDate() {
        return firstInstDate;
    }

    /**
     * Sets the value of the firstInstDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstInstDate(String value) {
        this.firstInstDate = value;
    }

    /**
     * Gets the value of the instAmount property.
     * 
     */
    public double getInstAmount() {
        return instAmount;
    }

    /**
     * Sets the value of the instAmount property.
     * 
     */
    public void setInstAmount(double value) {
        this.instAmount = value;
    }

    /**
     * Gets the value of the noOfInst property.
     * 
     */
    public int getNoOfInst() {
        return noOfInst;
    }

    /**
     * Sets the value of the noOfInst property.
     * 
     */
    public void setNoOfInst(int value) {
        this.noOfInst = value;
    }

    /**
     * Gets the value of the nextDemandDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextDemandDate() {
        return nextDemandDate;
    }

    /**
     * Sets the value of the nextDemandDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextDemandDate(String value) {
        this.nextDemandDate = value;
    }

    /**
     * Gets the value of the repayCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepayCode() {
        return repayCode;
    }

    /**
     * Sets the value of the repayCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepayCode(String value) {
        this.repayCode = value;
    }

    /**
     * Gets the value of the repayFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepayFrequency() {
        return repayFrequency;
    }

    /**
     * Sets the value of the repayFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepayFrequency(String value) {
        this.repayFrequency = value;
    }

}
