//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.28 at 12:29:36 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sampath.lk/SD/IIBFinacleIntegration/")
package biz.nable.sb.cor.transfer.soap.schemas.iib;
